#!/usr/bin/env sh

echo "Running lint-staged..."
npx lint-staged

changed_files=$(git diff --cached --name-only)

if echo "$changed_files" | grep -Eq "^\.env(\..*)?$|vite\.config\.ts|tailwind\.config\.ts|postcss\.config\.js|postcss\.config\.mjs"; then
  echo "You cannot modify protected config files."
  exit 1
fi

exit 0